- name: Install packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - apache2
    - libapache2-mod-php

- name: Setup index.html from template
  template:
    src: "{{ role_path }}/templates/index.j2"
    dest: /var/www/html/index.html

- name: Install actions
  copy:
     src: "{{ role_path }}/files/{{ item }}"
     dest: /var/www/html/
     owner: www-data
     mode: 0644
  with_items:
     - System
     - WiFiHotspot
     - DonkeyControl
